config/routes.rb
Rails.application.routes.draw do
  
  root "main#index"

  get "registration", to: "registration#new"
  post "registration", to: "registration#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  get "person_search", to: "person#index"
  get "person_results", to: "person#search"
  get "person_details", to:"person#details"
  post "person_favorite", to:"person#addFavorite"
  delete "person_favorite", to:"person#removeFavorite"
  put "person_favorite", to: "person#update"
  get "person_report", to: "person#report"
  get "person_full_report", to: "person#fullReport"

  get "course_search", to: "course#index"
  get "course_results", to: "course#search"
  get "course_details", to:"course#details"
  post "course_favorite", to:"course#addFavorite"
  delete "course_favorite", to:"course#removeFavorite"
  put "course_favorite", to: "course#update"
  get "course_report", to: "course#report"

  get "project_search", to: "project#index"
  get "project_results", to: "project#search"
  get "project_details", to:"project#details"
  post "project_favorite", to:"project#addFavorite"
  delete "project_favorite", to:"project#removeFavorite"
  put "project_favorite", to: "project#update"
  get "project_report", to: "project#report"

  get "thesis_search", to: "thesis#index"
  get "thesis_results", to: "thesis#search"
  get "thesis_details", to:"thesis#details"
  post "thesis_favorite", to:"thesis#addFavorite"
  delete "thesis_favorite", to:"thesis#removeFavorite"
  put "thesis_favorite", to: "thesis#update"
  get "thesis_report", to: "thesis#report"

  get "favorites", to: "favorites#list"

  get "reports", to: "search#menu"

  delete "logout", to: "sessions#destroy"
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    validates :objectId, presence: true
    validates :entryType, presence: true

    belongs_to :user
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def list
    @parameters = {
      "listName" => params[:listName],
      "paramName" =>params[:paramName],
      "order" => params[:order],   
    }

    if @parameters["order"].nil?
      @parameters["order"] = "desc"
    end
    unless ["title", "created_at"].include? @parameters["paramName"]
      @parameters["paramName"] = "title"
    end

    unless ["person", "thesis", "course", "project"].include? @parameters["listName"]
      @parameters["listName"] = "person"
    end

    @result = Favorite.where(entryType: @parameters["listName"]).order( @parameters["paramName"]+" "+  @parameters["order"])
    if @parameters["listName"] == "course"
      courses = Favorite.where(entryType: "course").to_a
      # courses.each do |res|
      #   puts res["title"]
      #   res["semester"] = get_semester_from_course_name(res["title"])
      # end
      @result = courses
    end

  end

  def get_semester_from_course_name(name)
    super(name)
  end

  def update
    super()
  end

end

app/views/favorites/list.html.erb
<%= stylesheet_link_tag "list", media: "all" %>
<%= stylesheet_link_tag "favorites-list", media: "all" %>
<% if Current.user %>
  <div class="header">
    <%= form_with url: "favorites", method: :get do |f| %>
      <%= f.label :listName, "List Name" %>
      <div class="select">
        <%= f.select :listName, [['Persons', 'person'], ['Courses', 'course'], ['Thesis', 'thesis'], ['Projects', 'project']], selected: @parameters["listName"] %>
      </div>
      <%= f.label :paramName, "Parameter to sort after" %>
      <div class="select">
        <%= f.select :paramName, [['Name', 'title'], ['Creation Date', 'created_at']], selected: @parameters["paramName"]  %>
      </div>
      <%= f.label :order, "Sorting order" %>
      <div class="select">
        <%= f.select :order, [['Descending', 'desc'], ['Ascending', 'asc']], selected: @parameters["order"]  %>
      </div>
      <%= f.submit "Load", class: "button-secondary load-button"%>
    <% end %>
  </div>
  <div class="list-container">
    <% if @result.present? %>
      <% @result.each_with_index do |element, index| %>
        <div class="list-item">
          <div class="text-info-box">
            <h2><%= element["title"] %></h2>
            <div class="controls">
              <% if element["entryType"] == "project" %>
                <%= link_to "Details", project_details_path(id: element["objectId"]), class: "button-secondary" %>
              <% elsif element["entryType"] == "thesis" %>
                <%= link_to "Thesis Details", thesis_details_path(id: element["objectId"]), class: "button-secondary" %>
              <% elsif element["entryType"] == "course" %>
                <%= link_to "Course Details", course_details_path(id: element["objectId"], semester:  element["title"].match(/\d{4}[WS]/)[0]), class: "button-secondary" %>
              <% elsif element["entryType"] == "person" %>
                <%= link_to "Person Details", person_details_path(id: element["objectId"]), class: "button-secondary" %>
              <% end %>
              <%= button_to "Remove from favorites", "#{element["entryType"]}_favorite", class: "button-secondary", method: :delete, params: { id: element["objectId"] } %>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <h1>Oh wow, so much empty :(</h1>
    <% end %>
  </div>
<% else %>
  <div>
    <span>You have to be logged in to perform this action.</span>
  </div>
<% end %>