config/routes.rb
Rails.application.routes.draw do
  
  root "main#index"

  get "registration", to: "registration#new"
  post "registration", to: "registration#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  get "person_search", to: "person#index"
  get "person_results", to: "person#search"
  get "person_details", to:"person#details"
  post "person_favorite", to:"person#addFavorite"
  delete "person_favorite", to:"person#removeFavorite"
  put "person_favorite", to: "person#update"
  get "person_report", to: "person#report"
  get "person_full_report", to: "person#fullReport"

  get "course_search", to: "course#index"
  get "course_results", to: "course#search"
  get "course_details", to:"course#details"
  post "course_favorite", to:"course#addFavorite"
  delete "course_favorite", to:"course#removeFavorite"
  put "course_favorite", to: "course#update"
  get "course_report", to: "course#report"

  get "project_search", to: "project#index"
  get "project_results", to: "project#search"
  get "project_details", to:"project#details"
  post "project_favorite", to:"project#addFavorite"
  delete "project_favorite", to:"project#removeFavorite"
  put "project_favorite", to: "project#update"
  get "project_report", to: "project#report"

  get "thesis_search", to: "thesis#index"
  get "thesis_results", to: "thesis#search"
  get "thesis_details", to:"thesis#details"
  post "thesis_favorite", to:"thesis#addFavorite"
  delete "thesis_favorite", to:"thesis#removeFavorite"
  put "thesis_favorite", to: "thesis#update"
  get "thesis_report", to: "thesis#report"

  get "favorites", to: "favorites#list"

  get "reports", to: "search#menu"

  delete "logout", to: "sessions#destroy"
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/person_controller.rb
class PersonController < SearchController

    def index
        search_type = {
            "model" => "Person",
            "search_term" => "Name"
        }
        super(search_type)
    end

    def search
        if !validate_query
            index
            render :index
            return
        end
        query = query_param[:query]
        url = get_search_url(query)
        super(url)
    end

    def get_search_url(query)
        return "https://tiss.tuwien.ac.at/api/person/v21/psuche?q=" + query;
    end

    def get_search_results(url)
        @results = super(url)
    end

    def details
        @id = params.require(:id)
        call_api(@id)
        @links_query = "#{@person["first_name"]}+#{@person["last_name"]}"
        @isFav = isFav()
        if(@isFav)
            element = Favorite.find_by(objectId: @id, entryType: Current.search_page_name, user_id: Current.user.id)
            @notes = element["notes"]
            @keywords = element["keywords"]
        end
        return @person
    end

    def call_api(id)
        uri = URI("https://tiss.tuwien.ac.at/api/person/v22/id/#{id}")
        response = Net::HTTP.get(uri)
        @person = JSON.parse(response)
    end

    def addFavorite
        super()
    end

    def removeFavorite
        super()
    end

    def isFav
        super()
    end

    def report
        super("person")
        @people = []
        for i in 0..@favorites.count-1
            @reportId = @favorites[i]["objectId"]
            p = call_api(@reportId)
            @people.push(p)
        end
    end

    
    def fullReport
        @data = []
        person = call_api(params[:id])
        @data.push(person)

        [CourseController, ProjectController, ThesisController].each do |controller|
            currController = controller.new
            url = currController.get_search_url(params[:query])
            results = currController.get_search_results(url)
            
            @data.push(results)
        end

        if !params[:search].nil? && params[:search].length > 0
            query = params[:search]
            regex = Regexp.new(query, Regexp::IGNORECASE)
            for i in 1..@data.length-1
                for j in 0..@data[i].length-1
                    @data[i][j]['title'] = @data[i][j]['title'].gsub(regex, '<span class="highlight">\0</span>').html_safe
                end
            end
        end
    end

    def update
        super()
    end

    def validate_query
        super(query_param)
    end

    private

    def query_param
        params[:query]
    end
end

app/views/person/details.html.erb
<%= stylesheet_link_tag "details", media: "all" %>
<div class="details">
  <div class="details-image-container">
    <% if @person["picture_uri"].present? %>
      <img src="https://tiss.tuwien.ac.at<%= @person["picture_uri"] %>" class="details-img">
    <% else %>
      <h4 class="no-image-text">No image available</h4>
    <% end %>
  </div>
  <div class="details-body">
    <h1 class="details-title"><%= @person["first_name"] %> <%= @person["last_name"] %></h1>
    <p class="details-text">
      Email: <%= @person["main_email"] %> <br>
      Phone Number:  <%= @person["main_phone_number"] %> <br>
      Preceeding Titles: <%= @person["preceding_titles"] %> <br>
      Postpositioned Titles: <%= @person["postpositioned_titles"] %></p>
  </div>
  <div class="details-controls">
    <div class="flex">
      <%= link_to "Courses", course_results_path(query: @links_query), class: "details-link link-primary" %>
      <%= link_to "Projects", project_results_path(query: @links_query), class: "details-link link-primary" %>
      <%= link_to "Theses", thesis_results_path(query: @links_query), class: "details-link link-primary" %>
      <%= link_to "Full Report", person_full_report_path(query: @links_query, id: @id), class: "details-link link-primary" %>
    </div>
  </div>
  <div class="augments">
    <% if !@isFav %>
      <%= form_with url: person_favorite_path, method: :post do |form| %>
        <div class="augments">
          <div class="augment-row">
            <label class="aug-label" for="keywords">Keywords:</label>
            <%= form.text_field :keywords, class: "inputs", placeholder: "Some keywords..." %>
          </div>
          <div class="augment-row">
            <label class="aug-label" for="notes">Personal Notes:</label>
            <%= form.text_area :notes, class: "area inputs", placeholder: "Some personal notes..." %>
          </div>
        </div>
        <%= hidden_field_tag :id, @person["tiss_id"] %>
        <%= hidden_field_tag :title, @person["first_name"] + " " + @person["last_name"] %>
        <%= form.submit "Add to favorites", class: "btn-to details-link link-primary details-button" %>
      <% end %>
    <% else %>
      <%= form_with url: person_favorite_path, method: :post do |form| %>
        <div class="augments">
          <div class="augment-row">
            <label class="aug-label" for="keywords">Keywords:</label>
            <%= form.text_field :keywords, class: "inputs", value: @keywords, placeholder: "Some keywords..." %>
          </div>
          <div class="augment-row">
            <label class="aug-label" for="notes">Personal Notes:</label>
            <%= form.text_area :notes, class: "area inputs",  value: @notes, placeholder: "Some personal notes..." %>
          </div>
        </div>
        <%= hidden_field_tag :id, @person["tiss_id"] %>
        <%= hidden_field_tag :title, @person["first_name"] + " " + @person["last_name"] %>
        <%= button_to "Update personal notes", person_favorite_path, class: "btn-to details-link link-primary details-button", method: :put %>
        <%= button_to "Remove from favorites", person_favorite_path, class: "btn-to details-link link-primary details-button", method: :delete, params: { id: @person["tiss_id"] } %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/person/fullReport.html.erb
<%= stylesheet_link_tag "details", media: "all" %>
<div class="report">
  <div class="search-field">
    <%= form_with url: person_full_report_path, method: :get do |form|%>
      <%= form.label :search%>
      <%= form.text_field :search, class: "full-size" %>
      <%= hidden_field_tag :query, params[:query] %>
      <%= hidden_field_tag :id, params[:id] %>
      <%= form.submit "Highlight" %>
    <%end %>
  </div>
  <div class="details">
    <div class="details-image-container">
      <% if @data[0]["picture_uri"].present? %>
        <img src="https://tiss.tuwien.ac.at<%= @data[0]["picture_uri"] %>" class="details-img">
      <% else %>
        <h4 class="no-image-text">No image available</h4>
      <% end %>
    </div>
    <div class="details-body">
      <h1 class="details-title"><%= @data[0]["first_name"] %> <%= @data[0]["last_name"] %></h1>
      <p class="details-text">
        Email: <%= @data[0]["main_email"] %> <br>
        Phone Number:  <%= @data[0]["main_phone_number"] %> <br>
        Preceeding Titles: <%= @data[0]["preceding_titles"] %> <br>
        Postpositioned Titles: <%= @data[0]["postpositioned_titles"] %></p>
    </div>
  </div>
  <div class="details">
    <h2>Courses</h2>
    <% if @data[1].length > 0%>
      <% @data[1].each do |course| %>
        <div>
          <h3 class="details-title"><%= course["title"] %> </h3>
        </div>
      <% end %>
    <% else%>
      <h3>There are no Courses associated with this lecturer.</h3>
    <%end%>
  </div>
  <div class="details">
    <% if @data[2].length > 0%>
      <h2>Projects</h2>
      <% @data[2].each do |project| %>
        <div>
          <h3 class="details-title"><%= project["title"] %> </h3>
        </div>
      <% end %>
    <% else%>
      <h3>There are no Projects associated with this lecturer.</h3>
    <%end%>
  </div>
  <div class="details">
    <h2>Thesis</h2>
    <% if @data[3].length > 0%>
      <% @data[3].each do |thesis| %>
        <div>
          <h3 class="details-title"><%= thesis["title"] %> </h3>
        </div>
      <% end %>
    <% else%>
      <h3>There are no Theses associated with this lecturer.</h3>
    <%end%>
  </div>
</div>

app/views/person/list.html.erb
<%= stylesheet_link_tag "list", media: "all" %>
<% if Current.user %>
  <div class="list-container">
    <% if @result.present? %>
      <% @result.each do |person| %>
        <div class="list-item">
          <% if person["adressbuch_benutzerbild"] %>
            <div class="img-container">
              <img class="person-img" src="<%= "https://tiss.tuwien.ac.at/" + person["adressbuch_benutzerbild"] %>">
            </div>
          <% end %>
          <div class="text-info-box">
            <span class="name"><%= person["firstname"] %></span>
            <span class="name"><%= person["lastname"] %></span>
            <span><%= person["prefixTitle"] %></span>
            <div class="controls person-controls">
              <%= link_to "Details", person_details_path(id: person["id"]), class: "button-secondary" %>
              <% if !person["isFav"] %>
                <%= button_to "Add favorites", person_favorite_path, class: "btn-to button-secondary", method: :post, params: { id: person["id"], title: person["firstname"] +" " + person["lastname"] }  %>
              <% else %>
                <%= button_to "Remove from favorites", person_favorite_path, class: "button-secondary", method: :delete, params: { id: person["id"] }  %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <h1>Oh wow, so much empty :(</h1>
    <% end %>
  </div>
<% else %>
  <div>
    <span>You have to be logged in to perform this action.</span>
  </div>
<% end %>

app/views/person/report.html.erb
<%= stylesheet_link_tag "list", media: "all" %>
<%= stylesheet_link_tag "favorites-list", media: "all" %>
<% if Current.user %>
  <div class="header">
    <%= form_with url: "/person_report", method: :get do |f| %>
      <%= f.check_box :showNotes, { checked: @parameters["showNotes"].to_i == 1 } %>
      <%= f.label :showNotes, "Show personal annotations" %>
      <%= f.submit "Generate", class: "button-secondary load-button"%>
      <p class="prompt">You can directly print from this page. All unnecessary text will be removed in the print view.</p>
    <% end %>
  </div>
  <div class="list-container">
    <% if @people.present? %>
      <% @people.each_with_index do |person, index| %>
        <div class="list-item">
          <div class="text-info-box">
            <h3><%= @favorites[index]["title"] %></h3>
            <p class="details-text">
              Email: <%= person["main_email"] %> <br>
              Phone Number:  <%= person["main_phone_number"] %> <br>
              Preceeding Titles: <%= person["preceding_titles"] %> <br>
              Postpositioned Titles: <%= person["postpositioned_titles"] %>
            </p>
            <% if @parameters["showNotes"].to_i == 1 %>
              <% if @favorites[index]["keywords"].present?%>
                <div class="info">
                  <span>Keywords: </span>
                  <span><%= @favorites[index].keywords %></span>
                </div>
              <%end%>
              <% if @favorites[index]["notes"].present?%>
                <div class="info">
                  <span>Personal Notes: </span>
                  <span><%= @favorites[index].keywords %></span>
                </div>
              <%end%>
            <%end%>
          </div>
        </div>
      <% end %>
    <% else %>
      <h1>Oh wow, so much empty :(</h1>
    <% end %>
  </div>
<% else %>
  <div>
    <span>You have to be logged in to perform this action.</span>
  </div>
<% end %>